export enum PROFILE_ACTIONS {
  USER = "USER",
  PROFILE = "PROFILE",
  CLINIC_SEARCH = "CLINIC_SEARCH",
  DOCTOR_SCHEDULE = "DOCTOR_SCHEDULE",
  REPORTS = "REPORTS",
}

export enum PROFILE_TYPES {
  MANAGER = "MANAGER",
  PATIANT = "PATIANT",
  DOCTOR = "DOCTOR",
}
